export { default as Hero } from "./Hero";
export { default as Stats } from "./Stats";
export { default as WhatWeDo } from "./WhatWeDo";
export { default as Differentiators } from "./Differentiators";
export { default as Industries } from "./Industries";
export { default as Process } from "./Process";
export { default as GlobalPresence } from "./GlobalPresence";
export { default as Guarantees } from "./Guarantees";
export { default as ContactForm } from "./ContactForm";
